version: '3.8'
services:
  service1:
    build: ./api1/application
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service2:
    build: ./api2/application
    ports:
    - target: 5000
      published: 5000
      protocol: tcp